# Generated by Django 4.0.3 on 2022-07-13 22:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnaire_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='experience',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
    ]
