# Generated by Django 4.0.3 on 2022-07-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategories',
            name='image',
        ),
    ]
